# Generated by Django 5.1 on 2024-10-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationdetail",
            name="id",
        ),
        migrations.AlterField(
            model_name="organizationdetail",
            name="ref_org_id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
