# Generated by Django 5.1 on 2024-10-07 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contactmanagement", "0003_alter_contact_company_delete_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("in_store", "In-Store"),
                            ("on_site", "On-Site"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "appointment_status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        max_length=100,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="contactmanagement.contact",
                    ),
                ),
            ],
        ),
    ]
