# Generated by Django 5.1 on 2024-10-07 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactmanagement", "0003_alter_contact_company_delete_company"),
        ("core", "0002_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organizationdetail",
            ),
        ),
    ]
