# Generated by Django 5.1 on 2024-10-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactmanagement", "0004_contact_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_work",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
