# Generated by Django 5.1 on 2024-10-16 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactmanagement", "0006_alter_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contactmanagement.address",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="source",
            field=models.CharField(
                blank=True, default="chatbot", max_length=100, null=True
            ),
        ),
    ]
